const XLSX = require('xlsx');
const fs = require('fs');

async function generateExcelFile(data) {
  const result = [];

  result.push([
    'Roll',
    'Name',
    'Class',
    'Bangla 1st Paper (CQ)',
    'Bangla 1st Paper (MCQ)',
    'Bangla 1st Paper (Total)',
    'Bangla 1st Paper (GPA)',
    'Bangla 2nd Paper (CQ)',
    'Bangla 2nd Paper (MCQ)',
    'Bangla 2nd Paper (Total)',
    'Bangla 2nd Paper (GPA)',
    'English 1st Paper (CQ)',
    'English 1st Paper (MCQ)',
    'English 1st Paper (Total)',
    'English 1st Paper (GPA)',
    'English 2nd Paper (CQ)',
    'English 2nd Paper (MCQ)',
    'English 2nd Paper (Total)',
    'English 2nd Paper (GPA)',
    'Math (CQ)',
    'Math (MCQ)',
    'Math (Total)',
    'Math (GPA)',
    'Science (CQ)',
    'Science (MCQ)',
    'Science (Total)',
    'Science (GPA)',
    'ICT (CQ)',
    'ICT (MCQ)',
    'ICT (Total)',
    'ICT (GPA)',
    'Religion (CQ)',
    'Religion (MCQ)',
    'Religion (Total)',
    'Religion (GPA)',
    'BGS (CQ)',
    'BGS (MCQ)',
    'BGS (Total)',
    'BGS (GPA)',
    'Agriculture (CQ)',
    'Agriculture (MCQ)',
    'Agriculture (Total)',
    'Agriculture (GPA)',
    'Final GPA'
  ]);

  for (let row of data) {
    result.push([
      row["Roll"],
      row["Name"],
      row["Class"],
      row["Bangla 1st Paper (CQ)"],
      row["Bangla 1st Paper (MCQ)"],
      row["Bangla 1st Paper (Total)"],
      row["Bangla 1st Paper (GPA)"],
      row["Bangla 2nd Paper (CQ)"],
      row["Bangla 2nd Paper (MCQ)"],
      row["Bangla 2nd Paper (Total)"],
      row["Bangla 2nd Paper (GPA)"],
      row["English 1st Paper (CQ)"],
      row["English 1st Paper (MCQ)"],
      row["English 1st Paper (Total)"],
      row["English 1st Paper (GPA)"],
      row["English 2nd Paper (CQ)"],
      row["English 2nd Paper (MCQ)"],
      row["English 2nd Paper (Total)"],
      row["English 2nd Paper (GPA)"],
      row["Math (CQ)"],
      row["Math (MCQ)"],
      row["Math (Total)"],
      row["Math (GPA)"],
      row["Science (CQ)"],
      row["Science (MCQ)"],
      row["Science (Total)"],
      row["Science (GPA)"],
      row["ICT (CQ)"],
      row["ICT (MCQ)"],
      row["ICT (Total)"],
      row["ICT (GPA)"],
      row["Religion (CQ)"],
      row["Religion (MCQ)"],
      row["Religion (Total)"],
      row["Religion (GPA)"],
      row["BGS (CQ)"],
      row["BGS (MCQ)"],
      row["BGS (Total)"],
      row["BGS (GPA)"],
      row["Agriculture (CQ)"],
      row["Agriculture (MCQ)"],
      row["Agriculture (Total)"],
      row["Agriculture (GPA)"],
      row["Final GPA"]
    ]);
  }

  const ws = XLSX.utils.aoa_to_sheet(result);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Class 10 Results');

  XLSX.writeFile(wb, 'Class_10_Results(1).xlsx');
}

const data = [
  {
    "Roll": "2024001",
    "Name": "Student 1",
    "Class": "10",
    "Bangla 1st Paper (CQ)": 45,
    "Bangla 1st Paper (MCQ)": 15,
    "Bangla 1st Paper (Total)": 60,
    "Bangla 1st Paper (GPA)": 3.5,
    "Bangla 2nd Paper (CQ)": 40,
    "Bangla 2nd Paper (MCQ)": 12,
    "Bangla 2nd Paper (Total)": 52,
    "Bangla 2nd Paper (GPA)": 3.0,
    "English 1st Paper (CQ)": 40,
    "English 1st Paper (MCQ)": 15,
    "English 1st Paper (Total)": 55,
    "English 1st Paper (GPA)": 3.2,
    "English 2nd Paper (CQ)": 42,
    "English 2nd Paper (MCQ)": 18,
    "English 2nd Paper (Total)": 60,
    "English 2nd Paper (GPA)": 3.6,
    "Math (CQ)": 50,
    "Math (MCQ)": 18,
    "Math (Total)": 68,
    "Math (GPA)": 3.9,
    "Science (CQ)": 48,
    "Science (MCQ)": 17,
    "Science (Total)": 65,
    "Science (GPA)": 3.7,
    "ICT (CQ)": 40,
    "ICT (MCQ)": 15,
    "ICT (Total)": 55,
    "ICT (GPA)": 3.3,
    "Religion (CQ)": 48,
    "Religion (MCQ)": 16,
    "Religion (Total)": 64,
    "Religion (GPA)": 3.6,
    "BGS (CQ)": 44,
    "BGS (MCQ)": 13,
    "BGS (Total)": 57,
    "BGS (GPA)": 3.4,
    "Agriculture (CQ)": 42,
    "Agriculture (MCQ)": 14,
    "Agriculture (Total)": 56,
    "Agriculture (GPA)": 3.4,
    "Final GPA": 3.7
  },
  {
    "Roll": "2024002",
    "Name": "Student 2",
    "Class": "10",
    "Bangla 1st Paper (CQ)": 45,
    "Bangla 1st Paper (MCQ)": 15,
    "Bangla 1st Paper (Total)": 60,
    "Bangla 1st Paper (GPA)": 3.5,
    "Bangla 2nd Paper (CQ)": 40,
    "Bangla 2nd Paper (MCQ)": 12,
    "Bangla 2nd Paper (Total)": 52,
    "Bangla 2nd Paper (GPA)": 3.0,
    "English 1st Paper (CQ)": 40,
    "English 1st Paper (MCQ)": 15,
    "English 1st Paper (Total)": 55,
    "English 1st Paper (GPA)": 3.2,
    "English 2nd Paper (CQ)": 42,
    "English 2nd Paper (MCQ)": 18,
    "English 2nd Paper (Total)": 60,
    "English 2nd Paper (GPA)": 3.6,
    "Math (CQ)": 50,
    "Math (MCQ)": 18,
    "Math (Total)": 68,
    "Math (GPA)": 3.9,
    "Science (CQ)": 48,
    "Science (MCQ)": 17,
    "Science (Total)": 65,
    "Science (GPA)": 3.7,
    "ICT (CQ)": 40,
    "ICT (MCQ)": 15,
    "ICT (Total)": 55,
    "ICT (GPA)": 3.3,
    "Religion (CQ)": 48,
    "Religion (MCQ)": 16,
    "Religion (Total)": 64,
    "Religion (GPA)": 3.6,
    "BGS (CQ)": 44,
    "BGS (MCQ)": 13,
    "BGS (Total)": 57,
    "BGS (GPA)": 3.4,
    "Agriculture (CQ)": 42,
    "Agriculture (MCQ)": 14,
    "Agriculture (Total)": 56,
    "Agriculture (GPA)": 3.4,
    "Final GPA": 3.7
  },
  {
    "Roll": "2024003",
    "Name": "Student 3",
    "Class": "10",
    "Bangla 1st Paper (CQ)": 45,
    "Bangla 1st Paper (MCQ)": 15,
    "Bangla 1st Paper (Total)": 60,
    "Bangla 1st Paper (GPA)": 3.5,
    "Bangla 2nd Paper (CQ)": 40,
    "Bangla 2nd Paper (MCQ)": 12,
    "Bangla 2nd Paper (Total)": 52,
    "Bangla 2nd Paper (GPA)": 3.0,
    "English 1st Paper (CQ)": 40,
    "English 1st Paper (MCQ)": 15,
    "English 1st Paper (Total)": 55,
    "English 1st Paper (GPA)": 3.2,
    "English 2nd Paper (CQ)": 42,
    "English 2nd Paper (MCQ)": 18,
    "English 2nd Paper (Total)": 60,
    "English 2nd Paper (GPA)": 3.6,
    "Math (CQ)": 50,
    "Math (MCQ)": 18,
    "Math (Total)": 68,
    "Math (GPA)": 3.9,
    "Science (CQ)": 48,
    "Science (MCQ)": 17,
    "Science (Total)": 65,
    "Science (GPA)": 3.7,
    "ICT (CQ)": 40,
    "ICT (MCQ)": 15,
    "ICT (Total)": 55,
    "ICT (GPA)": 3.3,
    "Religion (CQ)": 48,
    "Religion (MCQ)": 16,
    "Religion (Total)": 64,
    "Religion (GPA)": 3.6,
    "BGS (CQ)": 44,
    "BGS (MCQ)": 13,
    "BGS (Total)": 57,
    "BGS (GPA)": 3.4,
    "Agriculture (CQ)": 42,
    "Agriculture (MCQ)": 14,
    "Agriculture (Total)": 56,
    "Agriculture (GPA)": 3.4,
    "Final GPA": 3.7
},
  {
    "Roll": "2024004",
    "Name": "Student 4",
    "Class": "10",
    "Bangla 1st Paper (CQ)": 45,
    "Bangla 1st Paper (MCQ)": 15,
    "Bangla 1st Paper (Total)": 60,
    "Bangla 1st Paper (GPA)": 3.5,
    "Bangla 2nd Paper (CQ)": 40,
    "Bangla 2nd Paper (MCQ)": 12,
    "Bangla 2nd Paper (Total)": 52,
    "Bangla 2nd Paper (GPA)": 3.0,
    "English 1st Paper (CQ)": 40,
    "English 1st Paper (MCQ)": 15,
    "English 1st Paper (Total)": 55,
    "English 1st Paper (GPA)": 3.2,
    "English 2nd Paper (CQ)": 42,
    "English 2nd Paper (MCQ)": 18,
    "English 2nd Paper (Total)": 60,
    "English 2nd Paper (GPA)": 3.6,
    "Math (CQ)": 50,
    "Math (MCQ)": 18,
    "Math (Total)": 68,
    "Math (GPA)": 3.9,
    "Science (CQ)": 48,
    "Science (MCQ)": 17,
    "Science (Total)": 65,
    "Science (GPA)": 3.7,
    "ICT (CQ)": 40,
    "ICT (MCQ)": 15,
    "ICT (Total)": 55,
    "ICT (GPA)": 3.3,
    "Religion (CQ)": 48,
    "Religion (MCQ)": 16,
    "Religion (Total)": 64,
    "Religion (GPA)": 3.6,
    "BGS (CQ)": 44,
    "BGS (MCQ)": 13,
    "BGS (Total)": 57,
    "BGS (GPA)": 3.4,
    "Agriculture (CQ)": 42,
    "Agriculture (MCQ)": 14,
    "Agriculture (Total)": 56,
    "Agriculture (GPA)": 3.4,
    "Final GPA": 3.7
},
];

generateExcelFile(data);

// Class 9-10

/*
const XLSX = require('xlsx');
const fs = require('fs');

async function generateExcelFile(data) {
  const result = [];

  result.push([
    'Roll', 'Name', 'Class', 'Bangla 1st Paper (CQ)', 'Bangla 1st Paper (MCQ)', 'Bangla 1st Paper (Total)', 'Bangla 1st Paper (GPA)',
    'Bangla 2nd Paper (CQ)', 'Bangla 2nd Paper (MCQ)', 'Bangla 2nd Paper (Total)', 'Bangla 2nd Paper (GPA)',
    'English 1st Paper (CQ)', 'English 1st Paper (MCQ)', 'English 1st Paper (Total)', 'English 1st Paper (GPA)',
    'English 2nd Paper (CQ)', 'English 2nd Paper (MCQ)', 'English 2nd Paper (Total)', 'English 2nd Paper (GPA)',
    'Math (CQ)', 'Math (MCQ)', 'Math (Total)', 'Math (GPA)', 'Physics (CQ)', 'Physics (MCQ)', 'Physics (Total)', 'Physics (GPA)',
    'Chemistry (CQ)', 'Chemistry (MCQ)', 'Chemistry (Total)', 'Chemistry (GPA)', 'Biology (CQ)', 'Biology (MCQ)', 'Biology (Total)',
    'Biology (GPA)', 'ICT (CQ)', 'ICT (MCQ)', 'ICT (Total)', 'ICT (GPA)', 'Religion (CQ)', 'Religion (MCQ)', 'Religion (Total)',
    'Religion (GPA)', 'BGS (CQ)', 'BGS (MCQ)', 'BGS (Total)', 'BGS (GPA)', 'Higher Math (CQ)', 'Higher Math (MCQ)', 'Higher Math (Total)',
    'Higher Math (GPA)', 'Agriculture (CQ)', 'Agriculture (MCQ)', 'Agriculture (Total)', 'Agriculture (GPA)', 'Final GPA'
  ]);

  for (let row of data) {
    result.push([
      row["Roll"],
      row["Name"],
      row["Class"],
      row["Bangla 1st Paper (CQ)"],
      row["Bangla 1st Paper (MCQ)"],
      row["Bangla 1st Paper (Total)"],
      row["Bangla 1st Paper (GPA)"],
      row["Bangla 2nd Paper (CQ)"],
      row["Bangla 2nd Paper (MCQ)"],
      row["Bangla 2nd Paper (Total)"],
      row["Bangla 2nd Paper (GPA)"],
      row["English 1st Paper (CQ)"],
      row["English 1st Paper (MCQ)"],
      row["English 1st Paper (Total)"],
      row["English 1st Paper (GPA)"],
      row["English 2nd Paper (CQ)"],
      row["English 2nd Paper (MCQ)"],
      row["English 2nd Paper (Total)"],
      row["English 2nd Paper (GPA)"],
      row["Math (CQ)"],
      row["Math (MCQ)"],
      row["Math (Total)"],
      row["Math (GPA)"],
      row["Physics (CQ)"],
      row["Physics (MCQ)"],
      row["Physics (Total)"],
      row["Physics (GPA)"],
      row["Chemistry (CQ)"],
      row["Chemistry (MCQ)"],
      row["Chemistry (Total)"],
      row["Chemistry (GPA)"],
      row["Biology (CQ)"],
      row["Biology (MCQ)"],
      row["Biology (Total)"],
      row["Biology (GPA)"],
      row["ICT (CQ)"],
      row["ICT (MCQ)"],
      row["ICT (Total)"],
      row["ICT (GPA)"],
      row["Religion (CQ)"],
      row["Religion (MCQ)"],
      row["Religion (Total)"],
      row["Religion (GPA)"],
      row["BGS (CQ)"],
      row["BGS (MCQ)"],
      row["BGS (Total)"],
      row["BGS (GPA)"],
      row["Higher Math (CQ)"],
      row["Higher Math (MCQ)"],
      row["Higher Math (Total)"],
      row["Higher Math (GPA)"],
      row["Agriculture (CQ)"],
      row["Agriculture (MCQ)"],
      row["Agriculture (Total)"],
      row["Agriculture (GPA)"],
      row["Final GPA"]
    ]);
  }

  const ws = XLSX.utils.aoa_to_sheet(result);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Class 10 Results');

  XLSX.writeFile(wb, 'Class_10_Results.xlsx');
}

const data = [
  {
    "Roll": "2024001",
    "Name": "Student 1",
    "Class": "10",
    "Bangla 1st Paper (CQ)": 45,
    "Bangla 1st Paper (MCQ)": 15,
    "Bangla 1st Paper (Total)": 60,
    "Bangla 1st Paper (GPA)": 3.5,
    "Bangla 2nd Paper (CQ)": 40,
    "Bangla 2nd Paper (MCQ)": 12,
    "Bangla 2nd Paper (Total)": 52,
    "Bangla 2nd Paper (GPA)": 3.0,
    "English 1st Paper (CQ)": 40,
    "English 1st Paper (MCQ)": 15,
    "English 1st Paper (Total)": 55,
    "English 1st Paper (GPA)": 3.2,
    "English 2nd Paper (CQ)": 42,
    "English 2nd Paper (MCQ)": 18,
    "English 2nd Paper (Total)": 60,
    "English 2nd Paper (GPA)": 3.6,
    "Math (CQ)": 50,
    "Math (MCQ)": 18,
    "Math (Total)": 68,
    "Math (GPA)": 3.9,
    "Physics (CQ)": 48,
    "Physics (MCQ)": 17,
    "Physics (Total)": 65,
    "Physics (GPA)": 3.7,
    "Chemistry (CQ)": 47,
    "Chemistry (MCQ)": 16,
    "Chemistry (Total)": 63,
    "Chemistry (GPA)": 3.8,
    "Biology (CQ)": 45,
    "Biology (MCQ)": 14,
    "Biology (Total)": 59,
    "Biology (GPA)": 3.5,
    "ICT (CQ)": 40,
    "ICT (MCQ)": 15,
    "ICT (Total)": 55,
    "ICT (GPA)": 3.3,
    "Religion (CQ)": 48,
    "Religion (MCQ)": 16,
    "Religion (Total)": 64,
    "Religion (GPA)": 3.6,
    "BGS (CQ)": 44,
    "BGS (MCQ)": 13,
    "BGS (Total)": 57,
    "BGS (GPA)": 3.4,
    "Higher Math (CQ)": 50,
    "Higher Math (MCQ)": 20,
    "Higher Math (Total)": 70,
    "Higher Math (GPA)": 4.0,
    "Final GPA": 3.7
  },
  {
    "Roll": "2024002",
    "Name": "Student 2",
    "Class": "10",
    "Bangla 1st Paper (CQ)": 45,
    "Bangla 1st Paper (MCQ)": 15,
    "Bangla 1st Paper (Total)": 60,
    "Bangla 1st Paper (GPA)": 3.5,
    "Bangla 2nd Paper (CQ)": 40,
    "Bangla 2nd Paper (MCQ)": 12,
    "Bangla 2nd Paper (Total)": 52,
    "Bangla 2nd Paper (GPA)": 3.0,
    "English 1st Paper (CQ)": 40,
    "English 1st Paper (MCQ)": 15,
    "English 1st Paper (Total)": 55,
    "English 1st Paper (GPA)": 3.2,
    "English 2nd Paper (CQ)": 42,
    "English 2nd Paper (MCQ)": 18,
    "English 2nd Paper (Total)": 60,
    "English 2nd Paper (GPA)": 3.6,
    "Math (CQ)": 50,
    "Math (MCQ)": 18,
    "Math (Total)": 68,
    "Math (GPA)": 3.9,
    "Physics (CQ)": 48,
    "Physics (MCQ)": 17,
    "Physics (Total)": 65,
    "Physics (GPA)": 3.7,
    "Chemistry (CQ)": 47,
    "Chemistry (MCQ)": 16,
    "Chemistry (Total)": 63,
    "Chemistry (GPA)": 3.8,
    "Biology (CQ)": 45,
    "Biology (MCQ)": 14,
    "Biology (Total)": 59,
    "Biology (GPA)": 3.5,
    "ICT (CQ)": 40,
    "ICT (MCQ)": 15,
    "ICT (Total)": 55,
    "ICT (GPA)": 3.3,
    "Religion (CQ)": 48,
    "Religion (MCQ)": 16,
    "Religion (Total)": 64,
    "Religion (GPA)": 3.6,
    "BGS (CQ)": 44,
    "BGS (MCQ)": 13,
    "BGS (Total)": 57,
    "BGS (GPA)": 3.4,
    "Agriculture (CQ)": 42,
    "Agriculture (MCQ)": 14,
    "Agriculture (Total)": 56,
    "Agriculture (GPA)": 3.4,
    "Final GPA": 3.7
  },
    {
    "Roll": "2024003",
    "Name": "Student 3",
    "Class": "10",
    "Bangla 1st Paper (CQ)": 45,
    "Bangla 1st Paper (MCQ)": 15,
    "Bangla 1st Paper (Total)": 60,
    "Bangla 1st Paper (GPA)": 3.5,
    "Bangla 2nd Paper (CQ)": 40,
    "Bangla 2nd Paper (MCQ)": 12,
    "Bangla 2nd Paper (Total)": 52,
    "Bangla 2nd Paper (GPA)": 3.0,
    "English 1st Paper (CQ)": 40,
    "English 1st Paper (MCQ)": 15,
    "English 1st Paper (Total)": 55,
    "English 1st Paper (GPA)": 3.2,
    "English 2nd Paper (CQ)": 42,
    "English 2nd Paper (MCQ)": 18,
    "English 2nd Paper (Total)": 60,
    "English 2nd Paper (GPA)": 3.6,
    "Math (CQ)": 50,
    "Math (MCQ)": 18,
    "Math (Total)": 68,
    "Math (GPA)": 3.9,
    "Physics (CQ)": 48,
    "Physics (MCQ)": 17,
    "Physics (Total)": 65,
    "Physics (GPA)": 3.7,
    "Chemistry (CQ)": 47,
    "Chemistry (MCQ)": 16,
    "Chemistry (Total)": 63,
    "Chemistry (GPA)": 3.8,
    "Biology (CQ)": 45,
    "Biology (MCQ)": 14,
    "Biology (Total)": 59,
    "Biology (GPA)": 3.5,
    "ICT (CQ)": 40,
    "ICT (MCQ)": 15,
    "ICT (Total)": 55,
    "ICT (GPA)": 3.3,
    "Religion (CQ)": 48,
    "Religion (MCQ)": 16,
    "Religion (Total)": 64,
    "Religion (GPA)": 3.6,
    "BGS (CQ)": 44,
    "BGS (MCQ)": 13,
    "BGS (Total)": 57,
    "BGS (GPA)": 3.4,
    "Higher Math (CQ)": 50,
    "Higher Math (MCQ)": 20,
    "Higher Math (Total)": 70,
    "Higher Math (GPA)": 4.0,
    "Final GPA": 3.7
  },
  {
    "Roll": "2024004",
    "Name": "Student 4",
    "Class": "10",
    "Bangla 1st Paper (CQ)": 45,
    "Bangla 1st Paper (MCQ)": 15,
    "Bangla 1st Paper (Total)": 60,
    "Bangla 1st Paper (GPA)": 3.5,
    "Bangla 2nd Paper (CQ)": 40,
    "Bangla 2nd Paper (MCQ)": 12,
    "Bangla 2nd Paper (Total)": 52,
    "Bangla 2nd Paper (GPA)": 3.0,
    "English 1st Paper (CQ)": 40,
    "English 1st Paper (MCQ)": 15,
    "English 1st Paper (Total)": 55,
    "English 1st Paper (GPA)": 3.2,
    "English 2nd Paper (CQ)": 42,
    "English 2nd Paper (MCQ)": 18,
    "English 2nd Paper (Total)": 60,
    "English 2nd Paper (GPA)": 3.6,
    "Math (CQ)": 50,
    "Math (MCQ)": 18,
    "Math (Total)": 68,
    "Math (GPA)": 3.9,
    "Physics (CQ)": 48,
    "Physics (MCQ)": 17,
    "Physics (Total)": 65,
    "Physics (GPA)": 3.7,
    "Chemistry (CQ)": 47,
    "Chemistry (MCQ)": 16,
    "Chemistry (Total)": 63,
    "Chemistry (GPA)": 3.8,
    "Biology (CQ)": 45,
    "Biology (MCQ)": 14,
    "Biology (Total)": 59,
    "Biology (GPA)": 3.5,
    "ICT (CQ)": 40,
    "ICT (MCQ)": 15,
    "ICT (Total)": 55,
    "ICT (GPA)": 3.3,
    "Religion (CQ)": 48,
    "Religion (MCQ)": 16,
    "Religion (Total)": 64,
    "Religion (GPA)": 3.6,
    "BGS (CQ)": 44,
    "BGS (MCQ)": 13,
    "BGS (Total)": 57,
    "BGS (GPA)": 3.4,
    "Agriculture (CQ)": 42,
    "Agriculture (MCQ)": 14,
    "Agriculture (Total)": 56,
    "Agriculture (GPA)": 3.4,
    "Final GPA": 3.7
  },
];

generateExcelFile(data);*/